### ISSUE TITLE
Error using skills

### ISSUE THREAD

**Issue by yerktoyn** [Indyuce/mmoitems#106]
**Describe the bug**
`[20:16:23 ERROR]: Could not pass event PlayerInteractEvent to MMOItems v5.4.2
java.lang.NullPointerException: null
        at net.Indyuce.mmoitems.api.player.PlayerData.castAbilities(PlayerData.java:379) ~[?:?]
        at net.Indyuce.mmoitems.api.player.PlayerData.castAbilities(PlayerData.java:374) ~[?:?]
        at net.Indyuce.mmoitems.listener.PlayerListener.castClickAbilities(PlayerListener.java:60) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor525.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-260]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-260]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-260]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-260]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471) ~[patched_1.15.2.jar:git-Paper-260]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:438) ~[patched_1.15.2.jar:git-Paper-260]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:434) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1448) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1093) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1086) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1047) ~[patched_1.15.2.jar:git-Paper-260]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-260]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**To Reproduce**
After the update, we encountered an error. Weapon skills do not work and give an error. Weapon configuration example:
`QUEST_3:
  material: IRON_SWORD
  ability:
    ability1:
      type: FIRE_METEOR
      cooldown: 1.0
      knockback: 5.0
      mode: RIGHT_CLICK`

**Server info:**
 - PaperSpigot 1.15.2 260
 - MMOitems 5.4.2, MMOLib-1.1.2

**Additional context**
This problem is highly critical.

**Comment by yerktoyn** [comment]
This also happens with pure MMOItems configuration.

**Comment by LOVLOK2** [comment]
Same problem here.

**Comment by Kiragamisama** [comment]
Happen to me too on Paper 1.15.2 284 with MMOitem 5.4.2 and MMOLib 1.1.2
An error occurred when ability is used by right_click, left_click, shift_left_click and shift_right_click

**Comment by Artakia** [comment]
Yep, same problem here. Paper 1.15.2.

**Comment by AshenGaming** [comment]
Please try the latest dev builds - This has been fixed in build #259. If you still continue to have problems, please update this issue.
