### ISSUE TITLE
Plugin does not start.

### ISSUE THREAD

**Issue by Neclok** [Indyuce/mmoitems#15]
https://cdn.discordapp.com/attachments/369893285906612225/600837228578734080/unknown.png

`[23:58:49 INFO]: [MMOItems] Enabling MMOItems v4.7
[23:58:49 INFO]: [MMOItems] Detected Bukkit Version: v1_8_R3
[23:58:49 WARN]: [MMOItems] An error occured while reading the following type display: SHIELD
[23:58:49 WARN]: [MMOItems] An error occured while reading the following type display: SHIELD
[23:58:49 ERROR]: Error occurred while enabling MMOItems v4.7 (Is it up to date?)
java.lang.NoSuchFieldError: ENTITY_SWEEP_ATTACK
        at net.Indyuce.mmoitems.listener.PlayerListener.<clinit>(PlayerListener.java:46) ~[?:?]
        at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:139) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [server.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [server.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [server.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [server.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

I use legagy version 4.7 in minecraft 1.8.8 (latest version)

**Comment by Indyuce** [comment]
Will be fixed in the next update
