### ISSUE TITLE
ERROR]: Could not pass event EntityDamageByEntityEvent to MMOItems v4.7.3

### ISSUE THREAD

**Issue by qorgid125** [Indyuce/mmoitems#19]
**Describe the bug**

**To Reproduce**
[05:07:46 ERROR]: Could not pass event EntityDamageByEntityEvent to MMOItems v4.7.3
java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.AbstractPacket.sendPacket(AbstractPacket.java:64) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.sendDestroyEntitiesPacket(ProtocolLibHookImpl.java:270) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftVisibilityManager.sendDestroyPacketIfNear(CraftVisibilityManager.java:172) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftVisibilityManager.hideTo(CraftVisibilityManager.java:106) ~[?:?]
        at net.Indyuce.mmoitems.comp.holograms.HolographicDisplaysPlugin.displayIndicator(HolographicDisplaysPlugin.java:23) ~[?:?]
        at net.Indyuce.mmoitems.comp.holograms.HologramSupport.displayIndicator(HologramSupport.java:71) ~[?:?]
        at net.Indyuce.mmoitems.comp.holograms.HologramSupport$1.a(HologramSupport.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[craftbukkit.jar:git-Paper-107]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[craftbukkit.jar:git-Paper-107]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[craftbukkit.jar:git-Paper-107]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[craftbukkit.jar:git-Paper-107]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:223) ~[craftbukkit.jar:git-Paper-107]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:968) ~[craftbukkit.jar:git-Paper-107]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:867) ~[craftbukkit.jar:git-Paper-107]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1000) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity0(EntityLiving.java:1680) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityHuman.damageEntity0(EntityHuman.java:847) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1095) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityHuman.damageEntity(EntityHuman.java:770) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityPlayer.damageEntity(EntityPlayer.java:749) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityInsentient.C(EntityInsentient.java:1302) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityZombie.C(EntityZombie.java:320) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.PathfinderGoalMeleeAttack.a(SourceFile:139) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.PathfinderGoalMeleeAttack.e(SourceFile:131) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.PathfinderGoalZombieAttack.e(SourceFile:28) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.e(SourceFile:55) ~[craftbukkit.jar:git-Paper-107]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211]
        at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_211]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:80) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:661) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2526) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:503) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityMonster.movementTick(EntityMonster.java:22) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityZombie.movementTick(EntityZombie.java:207) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2315) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:274) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityMonster.tick(EntityMonster.java:36) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.EntityZombie.tick(EntityZombie.java:178) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.World.a(World.java:933) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[craftbukkit.jar:git-Paper-107]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[craftbukkit.jar:git-Paper-107]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.Validate
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[craftbukkit.jar:git-Paper-107]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[craftbukkit.jar:git-Paper-107]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 59 more

**Comment by Indyuce** [comment]
Nothing to do with MMOItems. Library issue, ask HolographicDisplays' dev.
