### ISSUE TITLE
Custom Block Drop Not Working + Error

### ISSUE THREAD

**Issue by MrBearLoL** [Indyuce/mmoitems#2]
[14:26:54 ERROR]: Could not pass event BlockBreakEvent to MMOItems v4.6.2
java.lang.NullPointerException: null
        at net.Indyuce.mmoitems.manager.ItemManager.getMMOItem(ItemManager.java:60) ~[?:?]
        at net.Indyuce.mmoitems.manager.ItemManager.getItem(ItemManager.java:84) ~[?:?]
        at net.Indyuce.mmoitems.api.DropItem.getItem(DropItem.java:69) ~[?:?]
        at net.Indyuce.mmoitems.api.DropItem.getItem(DropItem.java:65) ~[?:?]
        at net.Indyuce.mmoitems.api.DropTable.read(DropTable.java:54) ~[?:?]
        at net.Indyuce.mmoitems.manager.DropTableManager.b(DropTableManager.java:97) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor665.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-636]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-636]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-636]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:226) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1285) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-636]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-636]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-636]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by Indyuce** [comment]
How can I reproduce that issue?

**Comment by Indyuce** [comment]
Closing this ticket till more info is provided.
