### ISSUE TITLE
What this error

### ISSUE THREAD

**Issue by aatomant** [Indyuce/mmoitems#20]
[Server thread/WARN]: [MMOItems] Task #19806792 for MMOItems v4.7.3 generated an exception
java.lang.IllegalArgumentException: data should be class java.lang.Void got class org.bukkit.Particle$DustOptions
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnParticle(CraftWorld.java:2264) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnParticle(CraftWorld.java:2259) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnParticle(CraftWorld.java:2248) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnParticle(CraftWorld.java:2243) ~[patched_1.14.4.jar:git-Paper-135]
	at net.Indyuce.mmoitems.stat.data.ParticleData.display(ParticleData.java:124) ~[?:?]
	at net.Indyuce.mmoitems.particle.OffsetParticles.run(OffsetParticles.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-135]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

using in paper 1.14.4

**Comment by aatomant** [comment]
and 

[Server thread/WARN]: [MMOItems] Task #20935852 for MMOItems v4.7.3 generated an exception
java.lang.IllegalArgumentException: data should be class java.lang.Void got class org.bukkit.Particle$DustOptions
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnParticle(CraftWorld.java:2264) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnParticle(CraftWorld.java:2259) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnParticle(CraftWorld.java:2248) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnParticle(CraftWorld.java:2243) ~[patched_1.14.4.jar:git-Paper-135]
	at net.Indyuce.mmoitems.stat.data.ParticleData.display(ParticleData.java:124) ~[?:?]
	at net.Indyuce.mmoitems.particle.OffsetParticles.run(OffsetParticles.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-135]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by aatomant** [comment]
snapshot:5c6bc18:1418 paper

**Comment by Indyuce** [comment]
You are using a particle which is not supported by the item particles option. Some particles require block data like BLOCK_DUST or BLOCK_CRACK since they consist of a small piece of the block texture. MI do not support these particles (yet) because it does not provide an option to change the specified block
