### ISSUE TITLE
CustomDurability Error on Armor

### ISSUE THREAD

**Issue by chantong7945** [Indyuce/mmoitems#21]
**Describe the bug**
I got this bug when the custom durability on an armor piece reached zero and I got attacked when I put it on. This error was spamming the console and it somehow also still let the armor being able to work instead of asking me to repair it.

```
[19:05:55 ERROR]: Could not pass event EntityDamageByEntityEvent to MMOItems v4.7.3
java.lang.NullPointerException: null
at net.Indyuce.mmoitems.api.DurabilityItem.toItem(DurabilityItem.java:162) ~[?:?]
at net.Indyuce.mmoitems.api.DurabilityItem.decreaseDurability(DurabilityItem.java:122) ~[?:?]
at net.Indyuce.mmoitems.listener.CustomDurability.c(CustomDurability.java:86) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1018.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-629]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-629]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-629]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-629]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:104) ~[patched_1.13.2.jar:git-Paper-629]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:834) ~[patched_1.13.2.jar:git-Paper-629]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:733) ~[patched_1.13.2.jar:git-Paper-629]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:866) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1520) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity0(EntityHuman.java:905) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:993) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:818) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:704) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityInsentient.B(EntityInsentient.java:1248) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityZombie.B(EntityZombie.java:316) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.PathfinderGoalMeleeAttack.a(SourceFile:124) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.PathfinderGoalMeleeAttack.e(SourceFile:116) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.PathfinderGoalZombieAttack.e(SourceFile:28) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:108) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityInsentient.doTick(EntityInsentient.java:686) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2338) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityInsentient.movementTick(EntityInsentient.java:524) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityMonster.movementTick(EntityMonster.java:24) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityZombie.movementTick(EntityZombie.java:212) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2135) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:261) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityMonster.tick(EntityMonster.java:28) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.EntityZombie.tick(EntityZombie.java:186) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1561) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.World.g(World.java:1528) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1339) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-629]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-629]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Server info:**
This server is running Paper version git-Paper-629 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
MMOItems v4.7.3
 - Potential plugins linked to the issue -> None as not shown in the error

**Comment by Indyuce** [comment]
Will be fixed in the next updae
