### ISSUE TITLE
Error while hooking McMMO

### ISSUE THREAD

**Issue by Arkhtencial** [Indyuce/mmoitems#28]
**Describe the bug**
[20:30:12 INFO]: [MMOItems] Enabling MMOItems v4.7.10
[20:30:12 INFO]: [MMOItems] Loading crafting stations, please wait..
[20:30:12 INFO]: [MMOItems] Hooked onto HolographicDisplays
[20:30:12 INFO]: [MMOItems] Hooked onto PlaceholderAPI
[20:30:12 ERROR]: Error occurred while enabling MMOItems v4.7.10 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.player.PlayerEvent. Static getHandlerList method required!
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:584) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:526) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.Indyuce.mmoitems.comp.rpg.McMMOHook.<init>(McMMOHook.java:18) ~[MMOItems%20Premium.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
        at net.Indyuce.mmoitems.comp.rpg.RPGHandler$PluginEnum.load(RPGHandler.java:39) ~[MMOItems%20Premium.jar:?]
        at net.Indyuce.mmoitems.MMOItems.findRpgPlugin(MMOItems.java:395) ~[MMOItems%20Premium.jar:?]
        at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:242) ~[MMOItems%20Premium.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[20:30:12 INFO]: [MMOItemsPerWorldDrops] Enabling MMOItemsPerWorldDrops v1.1
[20:30:12 INFO]: [MMOItemsMana] Enabling MMOItemsMana v1.1
[20:30:12 INFO]: [MMOItemsMana] Hooked onto PlaceholderAPI
[20:30:12 ERROR]: Error occurred while enabling MMOItemsMana v1.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.player.PlayerEvent. Static getHandlerList method required!
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:584) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:526) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.Indyuce.mmoitems.addon.mana.comp.rpg.McMMOHook.<init>(McMMOHook.java:17) ~[MMOItems%20ManaAndStamina.jar:?]
        at net.Indyuce.mmoitems.addon.mana.Main.onEnable(Main.java:71) ~[MMOItems%20ManaAndStamina.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Expected behavior**
console spam

**Screenshots**
none, showed as console spam and totally freeze whole console

**Server info:**
 - SPIGOT-1.12.2-R0.1-SNAPSHOT
 -  MMOItems v4.7.10
 - Potential plugins linked to the issue of connection to McMMO

**Additional context**
already done hooking legacy-configs.zip into \MMOItems folder

**Comment by Indyuce** [comment]
Will be fixed in the newt update. 4.7.10 has other issues, you will have to downgrade to 4.7.9 for the time being.

**Comment by Arkhtencial** [comment]
[00:31:41 ERROR]: Error occurred while enabling MMOItems v4.7.9 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.player.PlayerEvent. Static getHandlerList method required!
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:584) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:526) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.Indyuce.mmoitems.comp.rpg.McMMOHook.<init>(McMMOHook.java:20) ~[MMOItems%20Premium.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
        at net.Indyuce.mmoitems.comp.rpg.handler.RPGHandler$PluginEnum.load(RPGHandler.java:59) ~[MMOItems%20Premium.jar:?]
        at net.Indyuce.mmoitems.MMOItems.findRpgPlugin(MMOItems.java:392) ~[MMOItems%20Premium.jar:?]
        at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:242) ~[MMOItems%20Premium.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[00:31:41 INFO]: [MMOItemsPerWorldDrops] Enabling MMOItemsPerWorldDrops v1.1
[00:31:41 INFO]: [MMOItemsMana] Enabling MMOItemsMana v1.1
[00:31:41 INFO]: [MMOItemsMana] Hooked onto PlaceholderAPI
[00:31:41 ERROR]: Error occurred while enabling MMOItemsMana v1.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.player.PlayerEvent. Static getHandlerList method required!
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:584) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:526) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.Indyuce.mmoitems.addon.mana.comp.McMMOHook.<init>(McMMOHook.java:17) ~[MMOItems%20ManaAndStamina.jar:?]
        at net.Indyuce.mmoitems.addon.mana.Main.onEnable(Main.java:66) ~[MMOItems%20ManaAndStamina.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
**Still the same issue no matter i downgrade it to 4.7.(9/8/7/6)**
