### ISSUE TITLE
MMOItems v4.7.9 - 1.14.4

### ISSUE THREAD

**Issue by minecraft7net** [Indyuce/mmoitems#32]
server 1.14.4 / spigot
[11:12:51] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-798ea6a-368f4e9 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

wg/we
[11:12:54] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.0.1-SNAPSHOT;4591-5f5c067
[11:12:54] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.1-SNAPSHOT;1961-93dae28

plugin loading
[11:12:54] [Server thread/WARN]: Plugin MMOItemsLegacyWG v1.0 does not specify an api-version.

https://pastebin.com/2m5QA5mn

server working
https://pastebin.com/wsuta7NT

[11:12:54] [Server thread/WARN]: Plugin MMOItemsLegacyWG v1.0 does not specify an api-version.
[11:12:55] [Server thread/INFO]: [MMOItems] Loading MMOItems v4.7.9
[11:12:55] [Server thread/INFO]: [MMOItems] Detected Bukkit Version: v1_14_R1
[11:12:55] [Server thread/INFO]: [MMOItems] Hooked onto WorldGuard
[11:12:56] [Server thread/INFO]: [MMOItemsPerWorldDrops] Loading MMOItemsPerWorldDrops v1.1
[11:12:56] [Server thread/INFO]: [MMOItemsMana] Loading MMOItemsMana v1.1
[11:12:56] [Server thread/INFO]: [MMOItemsLegacyWG] Loading MMOItemsLegacyWG v1.0
[11:12:56] [Server thread/ERROR]: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getFlagRegistry()Lcom/sk89q/worldguard/protection/flags/registry/FlagRegistry; initializing MMOItemsLegacyWG v1.0 (Is it up to date?)
        at net.Indyuce.mmoitems.comp.worldguard.legacy.Main.onLoad(Main.java:27) ~[?:?]
[11:13:36] [Server thread/INFO]: [MMOItems] Enabling MMOItems v4.7.9
[11:13:36] [Server thread/INFO]: [MMOItems] Loading crafting stations, please wait..
[11:13:36] [Server thread/INFO]: [MMOItems] Hooked onto HolographicDisplays
[11:13:36] [Server thread/INFO]: [MMOItems] Hooked onto PlaceholderAPI
[11:13:36] [Server thread/INFO]: [MMOItems] Hooked onto mcMMO
[11:13:36] [Server thread/INFO]: [MMOItems] Loading recipes, please wait...
[11:13:41] [Server thread/INFO]: [MMOItemsPerWorldDrops] Enabling MMOItemsPerWorldDrops v1.1
[11:13:42] [Server thread/INFO]: [MMOItemsMana] Enabling MMOItemsMana v1.1
[11:13:42] [Server thread/INFO]: [MMOItemsMana] Hooked onto PlaceholderAPI
[11:13:42] [Server thread/INFO]: [MMOItemsMana] Hooked onto mcMMO
[11:13:44] [Server thread/INFO]: [MMOItemsLegacyWG] Enabling MMOItemsLegacyWG v1.0
[11:13:44] [Server thread/INFO]: [MMOItemsLegacyWG] Successfully hooked onto MMOItems
[11:32:41] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MMOItems v4.7.9
        at net.Indyuce.mmoitems.comp.worldguard.legacy.Main.isFlagAllowed(Main.java:59) ~[MMOItems%20LegacyWG.jar:?]
        at net.Indyuce.mmoitems.api.player.PlayerData.castAbilities(PlayerData.java:339) ~[MMOItems%20Premium.jar:?]
        at net.Indyuce.mmoitems.listener.PlayerListener.g(PlayerListener.java:180) ~[MMOItems%20Premium.jar:?]

**Comment by Indyuce** [comment]
Read the installation guide. You are not supposed to use LegacyWG in 1.13+
