### ISSUE TITLE
Error while hooking McMMO #2

### ISSUE THREAD

**Issue by Arkhtencial** [Indyuce/mmoitems#33]
**Describe the bug**
[19:01:41 ERROR]: Error occurred while enabling MMOItems v4.7.11 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.player.PlayerEvent. Static getHandlerList method required!
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:584) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:526) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.Indyuce.mmoitems.comp.rpg.McMMOHook.<init>(McMMOHook.java:18) ~[MMOItems%20Premium.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
        at net.Indyuce.mmoitems.comp.rpg.RPGHandler$PluginEnum.load(RPGHandler.java:39) ~[MMOItems%20Premium.jar:?]
        at net.Indyuce.mmoitems.MMOItems.findRpgPlugin(MMOItems.java:395) ~[MMOItems%20Premium.jar:?]
        at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:242) ~[MMOItems%20Premium.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[19:01:41 INFO]: [MMOItemsPerWorldDrops] Enabling MMOItemsPerWorldDrops v1.2
[19:01:41 INFO]: [MMOItemsMana] Enabling MMOItemsMana v1.2
[19:01:41 INFO]: [MMOItemsMana] Hooked onto PlaceholderAPI
[19:01:41 ERROR]: Error occurred while enabling MMOItemsMana v1.2 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.player.PlayerEvent. Static getHandlerList method required!
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:584) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:526) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.Indyuce.mmoitems.addon.mana.comp.rpg.McMMOHook.<init>(McMMOHook.java:17) ~[MMOItems%20ManaAndStamina.jar:?]
        at net.Indyuce.mmoitems.addon.mana.Main.onEnable(Main.java:71) ~[MMOItems%20ManaAndStamina.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Server & plugin info:**
 - Spigot 1.12.2-R0.1-SNAPSHOT
 - Plugin Version: Tested with 4.7.10-re upload (4.7.11 to be exact) and older 4.7.9~4.7.6
 - Potential plugins linked to the issue **Couldn't hook McMMO** (Classic McMMO 1.5.10) (https://www.spigotmc.org/resources/official-mcmmo-classic.2445/)

**Comment by Indyuce** [comment]
MMOItems is built against the latest version of mcMMO overhaul. Can you try running MMOItems with the latest version of mcMMO classic (1.6+)?

**Comment by Arkhtencial** [comment]
Nope, only up to McMMO 1.5.10 are supported up till Minecraft 1.12.2, any further version McMMO will break error.

**Comment by Indyuce** [comment]
It looks like it's an issue on their end which I cannot do much about unfortunately.

**Comment by Arkhtencial** [comment]
Ok, fine, i will just now thise MMO items then.
