### ISSUE TITLE
Fatal error spam console

### ISSUE THREAD

**Issue by INTmAker** [Indyuce/mmoitems#42]
**Problem**
> [13:37:37 ERROR]: Could not pass event EntityDamageByEntityEvent to MMOItems v4.7
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:612) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1346) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:868) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1311) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1623) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at net.Indyuce.mmoitems.api.PlayerStats.getStat(PlayerStats.java:39) ~[MMOItems%20Legacy.jar:?]
at net.Indyuce.mmoitems.api.TypeSet.lambda$2(TypeSet.java:79) ~[MMOItems%20Legacy.jar:?]
at net.Indyuce.mmoitems.api.TypeSet.applyAttackEffect(TypeSet.java:135) ~[MMOItems%20Legacy.jar:?]
at net.Indyuce.mmoitems.api.item.weapon.Weapon.targetedAttack(Weapon.java:93) ~[MMOItems%20Legacy.jar:?]
at net.Indyuce.mmoitems.listener.ItemUse.b(ItemUse.java:128) ~[MMOItems%20Legacy.jar:?]
at sun.reflect.GeneratedMethodAccessor997.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-dcd1643-e60fc34]

**Server info:**
 - Spigot 1.12.2
 - MMOItems Legacy 4.7.3

**Comment by INTmAker** [comment]
> [18:03:40 ERROR]: Could not pass event EntityDamageByEntityEvent to MMOItems v4.7
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:612) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1346) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:846) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:868) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityMonster.B(EntityMonster.java:68) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityZombie.B(EntityZombie.java:202) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PathfinderGoalZombieAttack.e(SourceFile:28) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:664) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2097) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:507) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityMonster.n(EntityMonster.java:24) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityZombie.n(EntityZombie.java:155) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1946) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: x not finite
at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:115) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.util.Vector.checkFinite(Vector.java:624) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.setVelocity(CraftEntity.java:242) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at net.Indyuce.mmoitems.listener.PlayerListener.a(PlayerListener.java:66) ~[MMOItems%20Legacy.jar:?]
at sun.reflect.GeneratedMethodAccessor882.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-dcd1643-e60fc34]
... 35 more

**Comment by INTmAker** [comment]
PLEASE FIX

**Comment by Indyuce** [comment]
There are so many things wrong with your bug report.

First of all, the logs you provided are indicating that you are running MMOItems 4.7 whereas you stated that you were using the latest version available i.e MMOItems 4.7.3. I can understand you want that issue fixed as soon as possible, but throwing error logs at a developper, without even bothering about the most mediocre and least time consuming checks like that wastes both your time, and my time, because you have to install the latest version, see if the issue persists and potentially update your post, and because I have to write answers like this one.

You are not even using the latest version of the plugin. How could any developper even figure out what's happening if the build you are running does not match their updated build.

As it is clearly stated in the repo read-me, which I assume you have not read, you must include, in your issue ticket, the exact steps to be followed in order to reproduce the issue which I cannot see anywhere.

Although it might not have been your objective, issue tickets like yours are clearly disrespectful towards the dev's work, and . Fix your bug report and I'll gladly fix my plugin.

**Comment by INTmAker** [comment]
Ok sorry.

**Comment by INTmAker** [comment]
> [09:59:12 ERROR]: Could not pass event EntityDamageByEntityEvent to MMOItems v4.7.3
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:612) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1346) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:846) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:868) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityMonster.B(EntityMonster.java:68) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityZombie.B(EntityZombie.java:202) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PathfinderGoalZombieAttack.e(SourceFile:28) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:664) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2097) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:507) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityMonster.n(EntityMonster.java:24) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityZombie.n(EntityZombie.java:155) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1946) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: x not finite
at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:115) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.util.Vector.checkFinite(Vector.java:624) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.setVelocity(CraftEntity.java:242) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at net.Indyuce.mmoitems.listener.PlayerListener.a(PlayerListener.java:66) ~[MMOItems%20Legacy.jar:?]
at sun.reflect.GeneratedMethodAccessor599.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-dcd1643-e60fc34]
... 35 more

**Comment by Indyuce** [comment]
I just tried hitting a zombie on a 1.12.2 server with a non-op account, couldn't get any error to be displayed on the console.

**Comment by INTmAker** [comment]
What I can do?

**Comment by INTmAker** [comment]
And what Worldguard version should I use on spigot 1.12.2?

**Comment by INTmAker** [comment]
Developer, please help!!!

**Comment by INTmAker** [comment]
I also think this bug needs more investigation.

**Comment by INTmAker** [comment]
Do you need my configuration files?

**Comment by Indyuce** [comment]
You need to provide me the exact steps on how to reproduce the issue. Try running the plugin on a fresh server setup and see if it persists.

**Comment by INTmAker** [comment]
https://pastebin.com/Jrce8KKf

**Comment by INTmAker** [comment]
[22:57:39] [Server thread/INFO]: [MMOItems] Hooked onto HolographicDisplays
[22:57:39] [Server thread/INFO]: [MMOItems] Hooked onto PlaceholderAPI
[22:57:39] [Server thread/INFO]: [MMOItems] Hooked onto MythicMobs
[22:57:39] [Server thread/INFO]: [MMOItems] Hooked onto mcMMO

Maby some of this cause error?

**Comment by INTmAker** [comment]
Can I somehow disable hooks?

**Comment by Indyuce** [comment]
Try running the latest version of MMOItems on a fresh server setup and see if the issue persists.

**Comment by INTmAker** [comment]
There are no problems at fresh server.

**Comment by INTmAker** [comment]
Maby a worldguard issue?

**Comment by INTmAker** [comment]
Also, I use mythicmobs extension.

**Comment by Indyuce** [comment]
Try running MI on a fresh config setup to make sure it's not a simple config issue. If it's not, you can try removing your plugins one by one to determine what plugin is causing the issue. As I've said twice already, you need to determine how anyone can reproduce the issue on their end.

**Comment by INTmAker** [comment]
Oh it is NoCheatPlus can you please add support for it?

**Comment by Indyuce** [comment]
Will see what I can do. Anticheat support is not the priority of MMOItems development.
