### ISSUE TITLE
Console Spam while Attack Entity

### ISSUE THREAD

**Issue by Arkhtencial** [Indyuce/mmoitems#48]
**Console Log**
[04:15:58 ERROR]: Could not pass event EntityDamageByEntityEvent to MMOItems v4.7.16
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:612) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1346) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:868) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1311) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1625) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_221]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Skyblock.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.Indyuce.mmoitems.api.CustomSound
        at net.Indyuce.mmoitems.stat.CustomSounds.whenLoaded(CustomSounds.java:149) ~[MMOItems%20Premium.jar:?]
        at net.Indyuce.mmoitems.api.item.MMOItem.<init>(MMOItem.java:47) ~[MMOItems%20Premium.jar:?]
        at net.Indyuce.mmoitems.api.item.MMOItem.<init>(MMOItem.java:35) ~[MMOItems%20Premium.jar:?]
        at net.Indyuce.mmoitems.api.interaction.UseItem.<init>(UseItem.java:42) ~[MMOItems%20Premium.jar:?]
        at net.Indyuce.mmoitems.api.interaction.weapon.Weapon.<init>(Weapon.java:30) ~[MMOItems%20Premium.jar:?]
        at net.Indyuce.mmoitems.listener.ItemUse.b(ItemUse.java:123) ~[MMOItems%20Premium.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Skyblock.jar:git-Spigot-79a30d7-acbc348]
        ... 25 more

**Expected behavior**
Whenever player attack entity with MMOItem, this problem show up. Probably an API Error with MMOItems 4.7.16, It's completely fine while in 4.7.15 & 4.7.14

**Screenshots**
https://imgur.com/a/lB2IJD0
Guess it explained

**Server info:**
 - SPIGOT-1.12.2-R0.1-SNAPSHOT
 - MMOItems v4.7.14

**Additional context**
It's completely fine back in MMOItems 4.7.15

**Comment by Indyuce** [comment]
Will be fixed in the next update
