### ISSUE TITLE
Issue:Bug report

### ISSUE THREAD

**Issue by give5530** [Indyuce/mmoitems#5]
[01:05:43 WARN]: [MMOItems] Task #106 for MMOItems v4.6.1 generated an exception
java.lang.NullPointerException: null
        at net.Indyuce.mmoitems.MMOItems$2.run(MMOItems.java:173) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by give5530** [comment]
I'm 1.12.2

**Comment by Indyuce** [comment]
This error log doesn't tell much about the issue. Double check your console for other error logs especially on startup or when a player joins.

**Comment by give5530** [comment]
Is there a support server 1.12.2?

**Comment by give5530** [comment]
After detecting the plugin conflicts with RPGInventory!

**Comment by Indyuce** [comment]
MMOItems Legacy supports 1.12. Post any relevant logs.

**Comment by Indyuce** [comment]
Closed till more information is provided
