### ISSUE TITLE
plugin not works

### ISSUE THREAD

**Issue by hisotar** [Indyuce/mmoitems#54]
[20:37:35 ERROR]: [MMOItems] Plugin MMOItems v4.7.19b has failed to register events for class net.Indyuce.mmoitems.comp.mmocore.MMOCoreHook because net/Indyuce/mmocore/api/event/PlayerChangeClassEvent does not exist.
[20:37:35 ERROR]: Error occurred while enabling MMOItems v4.7.19b (Is it up to date?)
java.lang.NoSuchFieldError: attributeManager
at net.Indyuce.mmoitems.comp.mmocore.MMOCoreHook.<init(MMOCoreHook.java:60) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_201]
at net.Indyuce.mmoitems.comp.rpg.RPGHandler$PluginEnum.load(RPGHandler.java:35) ~[?:?]
at net.Indyuce.mmoitems.MMOItems.IaJ(MMOItems.java) ~[?:?]
at net.Indyuce.mmoitems.MMOItems.findRpgPlugin(MMOItems.java) ~[?:?]
at net.Indyuce.mmoitems.MMOItems.IaJ(MMOItems.java) ~[?:?]
at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-137]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-137]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-137]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-137]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-137]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-137]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.4.jar:git-Paper-137]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:871) ~[patched_1.14.4.jar:git-Paper-137]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by Indyuce** [comment]
Make sure you are using the very latest plugin builds for MMOItems and MMOCore. Download the latest versions over the MythicCraft website here:
https://www.mythicmobs.net/index.php?pages/download-mmocore/
https://www.mythicmobs.net/index.php?pages/download-mmoitems/
