### ISSUE TITLE
Plugin doesnt't Work in version 1.12 (No commend is working nothing happening)

### ISSUE THREAD

**Issue by AkionHD** [Indyuce/mmoitems#67]
****Describe the bug**
Hey ther ! 
My Name is Robin OK and i bought the Plugin MMOItems on 01.02.2020 on Spigot for 17,90€.
After i downloaded it i put it in the plugin folder of my server and the plugin MMoLib after that i restarted the server and went to the server and did the command /pl then i saw both of them green but if i do one command for example /mi Browse, ore /mi ,ore /mi help, nothing happened.
Please help me

**Here is the server llog!**
C:\Users\Thanos\Desktop\MC Tst>java -Xmx1G -jar spigot-1.12.jar
Loading libraries, please wait...
[22:49:04 INFO]: Starting minecraft server version 1.12
[22:49:04 INFO]: Loading properties
[22:49:04 INFO]: Default game type: SURVIVAL
[22:49:05 INFO]: This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[22:49:05 INFO]: Debug logging is disabled
[22:49:05 INFO]: Using 4 threads for Netty based IO
[22:49:05 INFO]: Server Ping Player Sample Count: 12
[22:49:05 INFO]: Generating keypair
[22:49:05 INFO]: Starting Minecraft server on *:25565
[22:49:05 INFO]: Using default channel type
[22:49:06 INFO]: Set PluginClassLoader as parallel capable
[22:49:06 INFO]: [MMOLib] Loading MMOLib v1.0.6
[22:49:06 INFO]: [MMOLib] Detected Bukkit Version: v1_12_R1
[22:49:06 INFO]: [ViaVersion] Loading ViaVersion v2.2.2
[22:49:06 INFO]: [ViaVersion] ViaVersion 2.2.2 is now loaded, injecting!
[22:49:06 INFO]: [ViaVersion] Loading 1.12.2 -> 1.13 block mapping...
[22:49:07 INFO]: [ViaVersion] Loading 1.12.2 -> 1.13 item mapping...
[22:49:07 INFO]: [ViaVersion] Loading new 1.13 tags...
[22:49:07 INFO]: [ViaVersion] Loading 1.12.2 -> 1.13 enchantment mapping...
[22:49:07 INFO]: [ViaVersion] Loading 1.12.2 -> 1.13 sound mapping...
[22:49:07 INFO]: [ViaVersion] Loading translation mapping
[22:49:07 INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 blockstate mapping...
[22:49:09 INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 block mapping...
[22:49:09 INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 item mapping...
[22:49:09 INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 sound mapping...
[22:49:09 INFO]: [ViaVersion] Loading 1.14 blockstates...
[22:49:09 INFO]: [ViaVersion] Loading 1.14 heightmap data...
[22:49:09 INFO]: [ViaVersion] Loading 1.14.4 -> 1.15 blockstate mapping...
[22:49:12 INFO]: [ViaVersion] Loading 1.14.4 -> 1.15 block mapping...
[22:49:12 INFO]: [ViaVersion] Loading 1.14.4 -> 1.15 item mapping...
[22:49:12 INFO]: [ViaVersion] Loading 1.14.4 -> 1.15 sound mapping...
[22:49:12 INFO]: [HolographicDisplays] Loading HolographicDisplays v2.4.1
[22:49:12 INFO]: [Holograms] Loading Holograms v2.12
[22:49:12 INFO]: [MMOItems] Loading MMOItems v5.3
[22:49:13 WARN]: [MMOItems] Could not register the type CROSSBOW: No enum constant org.bukkit.Material.WOODEN_PICKAXE
[22:49:13 WARN]: [MMOItems] Could not register the type GAUNTLET: No enum constant org.bukkit.Material.IRON_HORSE_ARMOR
[22:49:13 WARN]: [MMOItems] Could not register the type MUSKET: No enum constant org.bukkit.Material.IRON_HORSE_ARMOR
[22:49:13 WARN]: [MMOItems] Could not register the type SPEAR: No enum constant org.bukkit.Material.TRIDENT
[22:49:13 WARN]: [MMOItems] Could not register the type WHIP: No enum constant org.bukkit.Material.LEAD
[22:49:13 WARN]: [MMOItems] Could not register the type THRUSTING_SWORD: No enum constant org.bukkit.Material.GOLDEN_SWORD
[22:49:13 WARN]: [MMOItems] Could not register the type TALISMAN: No enum constant org.bukkit.Material.TOTEM_OF_UNDYING
[22:49:13 INFO]: [MMOItemsPerWorldDrops] Loading MMOItemsPerWorldDrops v1.2
[22:49:13 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[22:49:13 INFO]: Preparing level "world"
[22:49:13 INFO]: -------- World Settings For [world] --------
[22:49:13 INFO]: Nerfing mobs spawned from spawners: false
[22:49:13 INFO]: Item Merge Radius: 2.5
[22:49:13 INFO]: Item Despawn Rate: 6000
[22:49:13 INFO]: Arrow Despawn Rate: 1200
[22:49:13 INFO]: View Distance: 10
[22:49:13 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:49:13 INFO]: Zombie Aggressive Towards Villager: true
[22:49:13 INFO]: Experience Merge Radius: 3.0
[22:49:13 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[22:49:13 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[22:49:13 INFO]: Mob Spawn Range: 4
[22:49:13 INFO]: Cactus Growth Modifier: 100%
[22:49:13 INFO]: Cane Growth Modifier: 100%
[22:49:13 INFO]: Melon Growth Modifier: 100%
[22:49:13 INFO]: Mushroom Growth Modifier: 100%
[22:49:13 INFO]: Pumpkin Growth Modifier: 100%
[22:49:13 INFO]: Sapling Growth Modifier: 100%
[22:49:13 INFO]: Wheat Growth Modifier: 100%
[22:49:13 INFO]: NetherWart Growth Modifier: 100%
[22:49:13 INFO]: Vine Growth Modifier: 100%
[22:49:13 INFO]: Cocoa Growth Modifier: 100%
[22:49:13 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[22:49:13 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:49:13 INFO]: Random Lighting Updates: false
[22:49:13 INFO]: Max TNT Explosions: 100
[22:49:13 INFO]: Structure Info Saving: true
[22:49:13 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[22:49:14 INFO]: -------- World Settings For [world_nether] --------
[22:49:14 INFO]: Nerfing mobs spawned from spawners: false
[22:49:14 INFO]: Item Merge Radius: 2.5
[22:49:14 INFO]: Item Despawn Rate: 6000
[22:49:14 INFO]: Arrow Despawn Rate: 1200
[22:49:14 INFO]: View Distance: 10
[22:49:14 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:49:14 INFO]: Zombie Aggressive Towards Villager: true
[22:49:14 INFO]: Experience Merge Radius: 3.0
[22:49:14 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[22:49:14 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[22:49:14 INFO]: Mob Spawn Range: 4
[22:49:14 INFO]: Cactus Growth Modifier: 100%
[22:49:14 INFO]: Cane Growth Modifier: 100%
[22:49:14 INFO]: Melon Growth Modifier: 100%
[22:49:14 INFO]: Mushroom Growth Modifier: 100%
[22:49:14 INFO]: Pumpkin Growth Modifier: 100%
[22:49:14 INFO]: Sapling Growth Modifier: 100%
[22:49:14 INFO]: Wheat Growth Modifier: 100%
[22:49:14 INFO]: NetherWart Growth Modifier: 100%
[22:49:14 INFO]: Vine Growth Modifier: 100%
[22:49:14 INFO]: Cocoa Growth Modifier: 100%
[22:49:14 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[22:49:14 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:49:14 INFO]: Random Lighting Updates: false
[22:49:14 INFO]: Max TNT Explosions: 100
[22:49:14 INFO]: Structure Info Saving: true
[22:49:14 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[22:49:14 INFO]: -------- World Settings For [world_the_end] --------
[22:49:14 INFO]: Nerfing mobs spawned from spawners: false
[22:49:14 INFO]: Item Merge Radius: 2.5
[22:49:14 INFO]: Item Despawn Rate: 6000
[22:49:14 INFO]: Arrow Despawn Rate: 1200
[22:49:14 INFO]: View Distance: 10
[22:49:14 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:49:14 INFO]: Zombie Aggressive Towards Villager: true
[22:49:14 INFO]: Experience Merge Radius: 3.0
[22:49:14 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[22:49:14 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[22:49:14 INFO]: Mob Spawn Range: 4
[22:49:14 INFO]: Cactus Growth Modifier: 100%
[22:49:14 INFO]: Cane Growth Modifier: 100%
[22:49:14 INFO]: Melon Growth Modifier: 100%
[22:49:14 INFO]: Mushroom Growth Modifier: 100%
[22:49:14 INFO]: Pumpkin Growth Modifier: 100%
[22:49:14 INFO]: Sapling Growth Modifier: 100%
[22:49:14 INFO]: Wheat Growth Modifier: 100%
[22:49:14 INFO]: NetherWart Growth Modifier: 100%
[22:49:14 INFO]: Vine Growth Modifier: 100%
[22:49:14 INFO]: Cocoa Growth Modifier: 100%
[22:49:14 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[22:49:14 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:49:14 INFO]: Random Lighting Updates: false
[22:49:14 INFO]: Max TNT Explosions: 100
[22:49:14 INFO]: Structure Info Saving: true
[22:49:14 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[22:49:14 INFO]: Preparing start region for level 0 (Seed: 8329436851780791187)
[22:49:15 INFO]: Preparing spawn area: 6%
[22:49:17 INFO]: Preparing spawn area: 10%
[22:49:18 INFO]: Preparing spawn area: 13%
[22:49:19 INFO]: Preparing spawn area: 17%
[22:49:20 INFO]: Preparing spawn area: 21%
[22:49:21 INFO]: Preparing spawn area: 24%
[22:49:22 INFO]: Preparing spawn area: 28%
[22:49:23 INFO]: Preparing spawn area: 30%
[22:49:24 INFO]: Preparing spawn area: 34%
[22:49:25 INFO]: Preparing spawn area: 37%
[22:49:26 INFO]: Preparing spawn area: 41%
[22:49:27 INFO]: Preparing spawn area: 45%
[22:49:28 INFO]: Preparing spawn area: 49%
[22:49:29 INFO]: Preparing spawn area: 53%
[22:49:30 INFO]: Preparing spawn area: 56%
[22:49:31 INFO]: Preparing spawn area: 61%
[22:49:32 INFO]: Preparing spawn area: 64%
[22:49:33 INFO]: Preparing spawn area: 68%
[22:49:34 INFO]: Preparing spawn area: 72%
[22:49:35 INFO]: Preparing spawn area: 75%
[22:49:36 INFO]: Preparing spawn area: 80%
[22:49:37 INFO]: Preparing spawn area: 84%
[22:49:38 INFO]: Preparing spawn area: 89%
[22:49:39 INFO]: Preparing spawn area: 93%
[22:49:40 INFO]: Preparing spawn area: 97%
[22:49:41 INFO]: Preparing start region for level 1 (Seed: 8329436851780791187)
[22:49:42 INFO]: Preparing spawn area: 8%
[22:49:43 INFO]: Preparing spawn area: 15%
[22:49:44 INFO]: Preparing spawn area: 20%
[22:49:45 INFO]: Preparing spawn area: 26%
[22:49:46 INFO]: Preparing spawn area: 32%
[22:49:47 INFO]: Preparing spawn area: 37%
[22:49:48 INFO]: Preparing spawn area: 45%
[22:49:49 INFO]: Preparing spawn area: 52%
[22:49:50 INFO]: Preparing spawn area: 59%
[22:49:52 INFO]: Preparing spawn area: 65%
[22:49:53 INFO]: Preparing spawn area: 69%
[22:49:54 INFO]: Preparing spawn area: 74%
[22:49:55 INFO]: Preparing spawn area: 79%
[22:49:56 INFO]: Preparing spawn area: 84%
[22:49:57 INFO]: Preparing spawn area: 89%
[22:49:58 INFO]: Preparing spawn area: 95%
[22:49:59 INFO]: Preparing start region for level 2 (Seed: 8329436851780791187)
[22:50:00 INFO]: Preparing spawn area: 13%
[22:50:01 INFO]: Preparing spawn area: 22%
[22:50:02 INFO]: Preparing spawn area: 34%
[22:50:03 INFO]: Preparing spawn area: 45%
[22:50:04 INFO]: Preparing spawn area: 55%
[22:50:05 INFO]: Preparing spawn area: 67%
[22:50:06 INFO]: Preparing spawn area: 80%
[22:50:07 INFO]: Preparing spawn area: 94%
[22:50:07 INFO]: [MMOLib] Enabling MMOLib v1.0.6
[22:50:07 ERROR]: [MMOLib] Plugin MMOLib v1.0.6 has failed to register events for class net.mmogroup.mmolib.listener.event.ArmorEquipEventListener because org/bukkit/event/block/BlockDispenseArmorEvent does not exist.
[22:50:07 INFO]: [ViaVersion] Enabling ViaVersion v2.2.2
[22:50:07 INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.4.1
[22:50:08 INFO]: [Holograms] Enabling Holograms v2.12
[22:50:08 INFO]: [Holograms] HologramEntityController set to: com.sainttx.holograms.nms.v1_12_R1.HologramEntityControllerImpl
[22:50:08 INFO]: [MMOItems] Enabling MMOItems v5.3
[22:50:10 INFO]: [MMOItems] Loading crafting stations, please wait..
[22:50:11 WARN]: [MMOItems] arcane-forge: Could not load item option no-recipe
[22:50:11 WARN]: [MMOItems] arcane-forge: Could not load item option no-queue-item
[22:50:11 WARN]: [MMOItems] SWORD.SOULSTEALER - [Enchantments] unbreaking is not a valid enchantment name.
[22:50:11 WARN]: [MMOItems] MATERIAL.FIRE_ESSENCE - [Enchantments] unbreaking is not a valid enchantment name.
[22:50:11 WARN]: [MMOItems] CATALYST.FIRE_TOTEM - [Enchantments] unbreaking is not a valid enchantment name.
[22:50:11 WARN]: [MMOItems] GEM_STONE.BLAZE_SOUL - Could not read material from item, using default
[22:50:11 WARN]: [MMOItems] GEM_STONE.BLAZE_SOUL - [Enchantments] unbreaking is not a valid enchantment name.
[22:50:11 WARN]: [MMOItems] BOW.HELL_BOW - [Enchantments] unbreaking is not a valid enchantment name.
[22:50:11 WARN]: [MMOItems] BOW.HELL_BOW - [Enchantments] infinity is not a valid enchantment name.
[22:50:11 WARN]: [MMOItems] GREATSWORD.MOLTEN_BLADE - Could not read material from item, using default
[22:50:11 WARN]: [MMOItems] mythical-forge: wither-essence: Could not load ingredient 'vanilla WITHER_SKELETON_SKULL'
[22:50:11 WARN]: [MMOItems] BOW.MARKING_BOW - [Enchantments] unbreaking is not a valid enchantment name.
[22:50:11 WARN]: [MMOItems] ARMOR.CURSED_WITHER_SKULL - Could not read material from item, using default
[22:50:11 WARN]: [MMOItems] mythical-forge: dead-pharaoh-helmet: Could not load ingredient 'vanilla SKELETON_SKULL'
[22:50:11 WARN]: [MMOItems] mythical-forge: mossy-skeleton-skull: Could not load ingredient 'vanilla SKELETON_SKULL'
[22:50:11 WARN]: [MMOItems] mythical-forge: Could not load item option no-recipe
[22:50:11 WARN]: [MMOItems] mythical-forge: Could not load item option no-queue-item
[22:50:11 WARN]: [MMOItems] GREATSWORD.TWO_HANDED_STEEL_SWORD - [Enchantments] sharpness is not a valid enchantment name.
[22:50:11 WARN]: [MMOItems] GREATSWORD.TWO_HANDED_STEEL_SWORD - [Enchantments] unbreaking is not a valid enchantment name.
[22:50:11 WARN]: [MMOItems] GREATSWORD.HARDENED_STEEL_CLAYMORE - [Enchantments] sharpness is not a valid enchantment name.
[22:50:11 WARN]: [MMOItems] TOOL.STEEL_SHOVEL - Could not read material from item, using default
[22:50:11 WARN]: [MMOItems] steel-crafting-station: Could not load item option no-recipe
[22:50:11 WARN]: [MMOItems] steel-crafting-station: Could not load item option no-queue-item
[22:50:11 ERROR]: [MMOItems] Plugin MMOItems v5.3 has failed to register events for class net.Indyuce.mmoitems.listener.NewDurabilityListener because org/bukkit/event/player/PlayerItemMendEvent does not exist.
[22:50:11 INFO]: [MMOItems] Hooked onto HolographicDisplays
[22:50:11 INFO]: [MMOItems] Loading recipes, please wait...
[22:50:11 ERROR]: Error occurred while enabling MMOItems v5.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/inventory/RecipeChoice
        at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:236) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: org.bukkit.inventory.RecipeChoice
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        ... 12 more
[22:50:11 INFO]: [MMOItemsPerWorldDrops] Enabling MMOItemsPerWorldDrops v1.2
[22:50:11 INFO]: Done (58,178s)! For help, type "help" or "?"
[22:50:11 INFO]: [ViaVersion] ViaVersion detected server version: 1.12(335)
[22:50:12 WARN]: [ViaVersion] There is a newer version available: 2.2.3, you're on: 2.2.2
[22:50:15 WARN]: [Holograms] holograms.yml file had no 'holograms' section defined, no holograms loaded
[22:50:17 INFO]: UUID of player AkionHD is c68e33a3-b5b8-488b-bcea-8fb345ad0d87
[22:50:17 ERROR]: Could not pass event PlayerJoinEvent to MMOItems v5.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at net.Indyuce.mmoitems.listener.PlayerListener.d(PlayerListener.java:83) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        ... 14 more

**Server info:**
 - Spigot 1.12
 - Plugin MMOItems 5.3
-  Plugin MMOLib 1.0.6
-  Plugin Holograms 2.12
-  Plugin MMOItems PerWorldDrops 
- Plugin ViaVersion 2.2.2

I hope you can help me thanks.

MFG Robin

**Comment by Indyuce** [comment]
That issue has been fixed in the latest development builds (available over the MythicCraft forums). A fix will be available in the next Spigot build
