### ISSUE TITLE
Hey my plugin don't work

### ISSUE THREAD

**Issue by PMencrp** [Indyuce/mmoitems#7]
[18:05:58 ERROR]: Error occurred while enabling MMOItems v4.6.2 (Is it up to date?) 
java.lang.NullPointerException: null
at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at net.Indyuce.mmoitems.manager.ConfigManager.getStatFormat(ConfigManager.java:252) ~[?:?]
at net.Indyuce.mmoitems.manager.ConfigManager.reload(ConfigManager.java:222) ~[?:?]
at net.Indyuce.mmoitems.manager.ConfigManager.<init>(ConfigManager.java:156) ~[?:?]
at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:131) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-3d850ec-809c399]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

Hmmmmm?

**Comment by Indyuce** [comment]
Update to the latest version, I don't support older plugin versions

**Comment by PMencrp** [comment]
but latest version only 1.13 and 1.14

**Comment by PMencrp** [comment]
my server is 1.12.2 :(

**Comment by Indyuce** [comment]
Download MMOItems Legacy

**Comment by Trclu** [comment]
MMOItems Legacy is not operational in 1.12.2
It only supports 1.12.

**Comment by Indyuce** [comment]
Closed till more information is provided
