### ISSUE TITLE
MMOItem Doesnt work  1.12.2 ANd its updated too.

### ISSUE THREAD

**Issue by Haveyougonemad** [Indyuce/mmoitems#70]
Error occurred while enabling MMOItems v5.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org.bukkit.inventory.RecipeChoice
at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:236) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: org.bukkit.inventory.RecipeChoice
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.ClassLoader.loadClassHelper(Unknown Source) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_232]
... 12 more

**Comment by Indyuce** [comment]
That issue has been fixed in the latest dev builds

**Comment by Haveyougonemad** [comment]
Ok make sure to Realse that version fast
Regard,
Super
