### ISSUE TITLE
Can't add Gem to Item

### ISSUE THREAD

**Issue by KNNI** [Indyuce/mmoitems#94]
**Describe the bug**
Can't add default Gem to default Item.
by "default" I mean the default configuration

**To Reproduce**
1. take Gem
2. click with this gem on a item/weapon .. 
3. see console error.

**Expected behavior**
That this gem will add itself to the item/weapon
(but it doesn't)

**Server info:**
 - PaperSpigot Build 201 / MC 1.15.2
 - MMOItems v5.3.2
 - Potential plugins linked to the issue

**Additional context**
Error in the Console:
```
[22:09:27 ERROR]: Could not pass event InventoryClickEvent to MMOItems v5.3.2
java.lang.NoClassDefFoundError: net/mmogroup/mmolib/api/item/StoredTags
        at net.Indyuce.mmoitems.api.interaction.GemStone.applyOntoItem(GemStone.java:28) ~[?:?]
        at net.Indyuce.mmoitems.listener.ItemUse.e(ItemUse.java:257) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor462.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-201]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-201]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-201]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2333) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1034) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-201]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Indyuce** [comment]
Download your MMOLib to 1.0.9
