### ISSUE TITLE
Can't add Gem to Item

### ISSUE THREAD

**Issue by 1425115471** [Indyuce/mmoitems#95]
#==========Spigot 1.15.2
[23:20:18] [Server thread/ERROR]: Could not pass event InventoryClickEvent to MMOItems v5.3.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2148) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NoClassDefFoundError: net/mmogroup/mmolib/api/item/StoredTags
	at net.Indyuce.mmoitems.api.interaction.GemStone.applyOntoItem(GemStone.java:28) ~[?:?]
	at net.Indyuce.mmoitems.listener.ItemUse.e(ItemUse.java:257) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	... 17 more
Caused by: java.lang.ClassNotFoundException: net.mmogroup.mmolib.api.item.StoredTags
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at net.Indyuce.mmoitems.api.interaction.GemStone.applyOntoItem(GemStone.java:28) ~[?:?]
	at net.Indyuce.mmoitems.listener.ItemUse.e(ItemUse.java:257) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-ae72bf4-183139d]
	... 17 more
#=========PaperSpigot 1.15.2
[23:17:50] [Server thread/ERROR]: Could not pass event InventoryClickEvent to MMOItems v5.3.2
java.lang.NoClassDefFoundError: net/mmogroup/mmolib/api/item/StoredTags
	at net.Indyuce.mmoitems.api.interaction.GemStone.applyOntoItem(GemStone.java:28) ~[?:?]
	at net.Indyuce.mmoitems.listener.ItemUse.e(ItemUse.java:257) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor895.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2334) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1034) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: net.mmogroup.mmolib.api.item.StoredTags
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[Paper-1.15.2-b211.jar:git-Paper-209]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	... 21 more
#=======================================
Spigot 1.15.2
PaperSpigot 1.15.2
#==========
MMOItems v5.3.2
MMOLib-1.0.10

**Comment by Indyuce** [comment]
Download your MMOLib to 1.0.9
